import requests
import os
from dotenv import load_dotenv, find_dotenv
from functions.logger import logger, console_handler
from sqlalchemy import create_engine
from http.cookiejar import MozillaCookieJar


load_dotenv(find_dotenv())

# get cookies
# https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc/related
# use this extensions for getting cookies

cookies = MozillaCookieJar("configs/cookie.txt")
cookies.load(ignore_discard=True, ignore_expires=True)

# fetch jsessionid for headers

for cookie in cookies:
    if cookie.name == "JSESSIONID":
        JSESSIONID = cookie.value.strip('"')
        break


headers = {
 'csrf-token': JSESSIONID,
 'accept': 'application/vnd.linkedin.normalized+json+2.1',
 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36'
}


# Database Information

DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST_IP = os.getenv("DB_HOST_IP")
DB_NAME = os.getenv("DB_NAME")



geoid_dict = {"turkey": "102105699", "germany": "101282230", "switzerland": "106693272", "usa": "103644278",
              "france": "105015875", "canada": "101174742", "denmark": "104514075", "united kingdom": "101165590",
              "norway": "103819153", "sweden": "105117694", "poland": "105072130", "netherlands": "102890719",
              "italy": "103350119", "japan": "101355337", "hungary": "100288700", "south africa": "104035573",
              "argentina": "100446943", "china": "102890883", "czechia": "104508036", "russia": "101728296",
              "spain": "105646813", "qatar": "104170880", "australia": "101452733", "united arab emirates ": "104305776",
              "india": "102713980", "saudi arabia": "100459316", "south korea": "105149562", "israel": "101620260",
              "lithuania": "101464403", "romania": "106670623", "crotia": "104688944", "bulgaria": "105333783",
              "serbia": "101855366", "greece": "104677530", "azerbaijan": "103226548", "ukraine": "102264497"}

custom_stopwords = ['experience', 'skills', 'work', 'business', 'science', 'years',
                                               'candidates', 'team', 'required', 'technical', 'development',
                                               'solutions', 'working', 'job', 'knowledge', 'degree',
                                               'engineering', 'requirements', 'computer', 'ability', 'management',
                                               'support', 'tools', 'position', 'clients', 'systems', 'including',
                                               'strong', 'information', 'statistical', 'learning', 'design', 'new',
                                               'related', 'technologies', 'time', 'level', 'develop', 'project', 'skill',
                                               'models', 'communication', 'complex', 'statistics',  'business',
                                               'candidates', 'experience', 'science', 'skills', 'team', 'work',
                                               'years', 'client', 'engineer', 'machine', 'need', 'preferred', 'projects',
                                               'role', 'software', 'cloud', 'industry', 'large', 'looking', 'programming',
                                               'services', 'technology', 'building', 'database', 'opportunity', 'quality',
                                               'research', 'understanding', 'apply', 'build', 'provide', 'reporting',
                                               'responsibilities', 'use', 'based', 'best', 'big', 'candidate', 'company',
                                               'create', 'databases', 'description', 'developing', 'enhancement',
                                               'environment',  'excellent', 'help',  'life', 'like', 'location', 'modeling',
                                               'needs', 'performance', 'problems', 'process', 'processes', 'processing',
                                               'product', 'qualifications', 'reports', 'scientist', 'sources',
                                               'teams', 'techniques', 'understand', 'visualization', 'written', 'able',
                                               'advanced', 'applications',  'bachelor', 'benefits',
                                               'customer', 'education', 'ensure', 'expertise', 'field', 'health',
                                               'high', 'identify', 'implement', 'improve', 'insights', 'intelligence',
                                               'language', 'methods', 'multiple', 'organization', 'problem', 'relevant',
                                               'remote', 'security', 'stakeholders', 'verbal', 'world', 'access',
                                               'additional', 'algorithms', 'application', 'architecture', 'assist',
                                               'career', 'code', 'communicate', 'creating', 'customers', 'datasets',
                                               'day', 'deliver', 'disability', 'driven', 'duties', 'effectively',
                                               'employees', 'employer', 'employment', 'end', 'enterprise', 'entry',
                                               'equal', 'equivalent', 'functional', 'good', 'hands', 'highly', 'include',
                                               'integration', 'internal', 'issues', 'jobs', 'kelly', 'key', 'lack',
                                               'languages', 'long', 'maintain', 'market', 'master', 'mathematics',
                                               'meet', 'minimum', 'mining', 'mission', 'model', 'motivated', 'open',
                                               'operations', 'opportunities', 'people', 'perform', 'platform', 'plus',
                                               'practices', 'products', 'programs', 'providing', 'quantitative',
                                               'responsible', 'results', 'self', 'senior', 'service', 'sets', 'solving',
                                               'span', 'stakeholders', 'status', 'synergisticit', 'tech', 'term', 'test',
                                               'testing', 'value', 'variety', 'verbal', 'vision', 'want', 'world',
                                               "attention", "background", "capabilities",
                                               "collaborate", "community", "companies", "concepts", "contract", "critical",
                                               "decision", "deep", "desired", "different", "drive", "employee",
                                               "engineers", "existing", "expert", "external", "family", "fast",
                                               "filing", "findings", "focus", "following", "functions", "future", "goals",
                                               "great", "healthcare", "implementation", "independently", "infrastructure",
                                               "interviews", "join", "know", "lead", "leading", "learn", "managing", "medical",
                                               "members", "national", "needed", "offer", "operational", "outcomes",
                                               "paid", "plan", "plans", "platforms", "predictive", "production",
                                               "professional", "proficiency", "program", "qualified", "range", "relational",
                                               "resume", "right", "sans", "scientists", "scripting",  "solve", "standards",
                                               "state", "tasks", "text", "title", "trends", "visa", "writing", "year",
                                               "agile", "appropriate", "assigned", "automation", "bachelors", "benefit",
                                               "care", "careers", "challenges", "check", "citizens", "clinical",
                                               "collection", "committed",  "core", "cross", "current", "dashboards",
                                               "decisions", "designing", "duration", "electrical", "essential", "federal",
                                               "financial", "gender", "general", "governance", "growing", "having", "hybrid",
                                               "impact", "implementing", "innovative", "junior", "learner", "local",
                                               "making", "manage", "masters", "months", "non", "optimization", "partners",
                                               "party", "patterns", "phone", "portfolio", "posting", "procedures",
                                               "questions", "real", "seeking", "selection", "set", "similar", "source",
                                               "talent", "technically", "user", "users", "veteran", "wants", "way",
                                               "activities", "areas", "automated", "available", "bring", "challenging",
                                               "change", "closely", "computing", "creates", "culture", "currently",
                                               "delivery", "developers", "digital", "diverse", "document", "documentation",
                                               "enhance", "extension",  "gain",  "government", "group", "improvement",
                                               "insurance", "interested", "leadership", "maintaining", "methodologies",
                                               "metrics", "onsite", "organizational", "orientation", "origin", "person",
                                               "planning", "proficient", "queries", "query", "race", "recommendations",
                                               "religion", "report", "salary", "series", "size", "skiltrek", "solution",
                                               "staff", "stand", "strategies", "structured", "success", "training",
                                               "transformation", "unstructured", "visas", "accuracy", "applied", "applying",
                                               "center", "coding", "come", "competency", "contribute", "days", "define",
                                               "demonstrated", "department", "details", "direct", "discipline", "effective",
                                               "efficiency", "efforts", "enable", "ensuring", "exceptional", "expected",
                                               "experienced", "familiarity", "finding",  "global", "graduates", "growth",
                                               "identity", "individual", "initiatives", "interview", "levels", "limited",
                                               "optimize", "partner", "pay", "policies", "present", "protected", "provides",
                                               "regression", "requirement", "resource", "sexual", "specific", "standard",
                                               "strategic", "strategy", "successful", "summary", "supporting", "type",
                                               "week", "works", "abilities", "action", "base", "basic", "better", "card",
                                               "cleaning", "clearance", "collaboration", "color", "common", "conduct",
                                               "consulting", "control", "cycle", "date", "deliverables", "dental",
                                               "distributed", "efficient", "experts", "extract", "focused", "hours",
                                               "individuals", "jobseekers", "latest", "law", "marketing", "match",
                                               "monitoring", "necessary", "oriented", "paypal", "performs", "proven",
                                               "providers", "reached", "resources", "risk", "scalable",
                                               "scripts", "site", "subject", "suite", "wide",  "actionable", "active",
                                               "applicants", "artificial", "break", "calls", "categories", "central",
                                               "clear", "commercial", "deployment", "develops", "difficulty",
                                               "dynamic", "employed", "environments", "especially", "fall", "firm",
                                               "flexible", "green", "hire", "hiring", "ideas", "identifying", "interpersonal",
                                               "leave", "links", "member", "missing", "natural", "opt", "picked", "primary",
                                               "programmers", "regard", "schedule", "sex", "share", "shortlisted",
                                               "stem", "tables", "university", "welcome", "account", "ad", "address", "age",
                                               "area", "assists","basis", "believe", "changes",
                                               "clustering", "compensation", "complete", "compliance", "components",
                                               "cracking", "creative", "direction", "domain", "execute", "forecasting",
                                               "graph", "grow", "helped", "ideal", "inclusive", "lucida", "mindset",
                                               "paced", "preparation", "recent", "requires", "sales", "small",
                                               "specifications", "staffing", "thousands", "transform", "translate",
                                               "acquisition", "agency", "approach", "approaches", "availability", "cases",
                                               "competitive", "considered", "contact", "directly", "helps", "interpret",
                                               "leverage", "load", "maintenance", "managers", "matter", "nice", "operating",
                                               "order", "performing", "personal", "policy", "presentation", "quickly",
                                               "requests", "rest", "review", "scrum", "search", "structures", "sure",
                                               "thinking", "tool",  "values", "visit", "write", "actively", "applicable", "aspects",
                                               "assess", "automate", "certification", "certifications",
                                               "collaborative", "connect", "designs", "developer", "excellence", "execution",
                                               "extraction", "features", "finance", "improvements", "ingestion", "manager",
                                               "mapping", "number", "objectives", "office", "oracle", "passion",
                                               "possess", "potential", "presentations", "principles", "roles", "stack",
                                               "start", "travel", "usa", "utilize", "accommodation", "amounts",
                                               "assistance", "combination", "delivering", "detailed", "determine", "economics",
                                               "enjoy", "free", "generate", "goal", "guidance", "innovation", "inquisitive",
                                               "inquisitiveexperience", "meaningful", "meetings", "monitor", "oral",
                                               "organize", "prioritize", "regards", "studies", "study", "supports",
                                               "tests", "tiktok", "timely", "validation", "word", "associated", "balance",
                                               "continuous",  "creation", "evaluate", "experiences", "files", "guide",
                                               "integrate", "labs", "manipulation", "math", "methodology", "packages",
                                               "prepare", "purpose",  "responsibility", "sciences", "scientific", "short",
                                               "skilled", "social", "supply", "times", "today", "trees", "utilizing",
                                               "achieve", "administration", "assets", "audiences", "broad", "content",
                                               "coordinate", "dedicated", "extensive", "fit", "gathering", "includes",
                                               "integrity", "ithighly", "manner", "note", "offers", "practice", "prior",
                                               "professionals", "rate", "record", "regulatory", "seekers", "varma", "ways",
                                               "apis", "communities", "diversity", "file", "major", "measurement", "neural",
                                               "overall", "package", "participate", "phd", "preferably", "public", "reasonable",
                                               "require", "scope", "send", "sense", "serve", "track", "trauma", "troubleshoot",
                                               "walmart", "affirmative", "award", "certified", "clean", "comprehensive",
                                               "demonstrate", "fully", "getting", "given", "helping", "holidays",
                                               "jira", "modern", "networks", "passionate", "perks", "reliability",
                                               "reputation", "workflow", "addition", "architectures",
                                               "class", "cleansing", "collaborates", "comfortable", "cost", "custom",
                                               "defining", "emr", "energy","exposure", "expression", "familiar",
                                               "feedback", "grant", "human", "structure", "unique", "workflows",
                                               "art", "built", "clearly", "documents", "evaluation", "fields",
                                               "optimal", "positions", "practical", "reach", "resolve",
                                               "rules", "settle", "step", "types", "updated", "western",
                                               "behavioral", "claims", "communicating", "dod", "hard", "input", "military",
                                               "mismatch", "month", "positive", "possible", "raw", "receive", "recommend",
                                               "toolsexcellent", "architect", "capable", "capacity", "case", "convert",
                                               "dashboard", "discovery", "eligible", "email", "events", "function", "let",
                                               "located", "metadata", "sick", "understands", "union", "asset", "collect",
                                               "cyber", "cycleknowledge", "databricks", "edge", "faculty", "frameworks",
                                               "institute", "link", "multi", "options", "overview", "physics",
                                               "player", "progress", "relationships", "reliable", "server", "storage",
                                               "streaming", "troubleshooting", "unit", "unix", "warehouses", "warehousing",
                                               "willing", "accurate", "analyses", "analysis", "analyst", "analysts",
                                               "analytic", "analytical", "analytics", "analyze", "analyzing", "bonus",
                                               "boot", "campus", "centric", "classification", "collaboratively", "depth",
                                               "discrimination", "duke", "equity", "formats", "leveraging", "libraries",
                                               "lifecycle", "line", "linear", "memphis",  "nature", "physical", "play",
                                               "significant", "spending", "states", "supervisor", "voices", "york",
                                               "ai", "businesses", "category", "cd", "colleagues", "commitment",
                                               "completion", "computational", "daily", "defense", "desire",
                                               "difficult", "directed", "ensures", "event", "groups", "informatica",
                                               "investment", "operate", "operation", "owned", "pipeline", "pipelines",
                                               "polygraph", "power", "presenting", "produce", "promise", "protection",
                                               "recruitment", "reviews", "savings", "specifically", "think", "uses",
                                               "vendors", "chain", "citizenship", "click", "college", "conducting",
                                               "consistent", "credit", "dallas", "deploy", "emerging", "exciting", "formal",
                                               "fortune", "fresh", "friendly", "google", "important", "improving",
                                               "integrated", "lake", "leaders", "lives", "llc", "logic", "manipulate",
                                               "modelling", "ms", "optimizing", "organizations", "owners", "pm", "provided",
                                               "records", "registry", "retirement", "school", "space", "update", "va",
                                               "wanting", "winning", "biostatistics", "bs", "capture", "ci", "collecting",
                                               "cybersecurity", "electronic", "elements", "established", "inclusion",
                                               "interactive", "interface", "involved", "largest", "legal", "maintains",
                                               "migration",  "minimal", "object", "ongoing", "perspectives", "points",
                                               "prefer", "priorities", "provider", "red", "request", "responses", "resumes",
                                               "robust", "secret",  "setting", "stores", "task", "techstars", "tennessee",
                                               "usage", "willingness" "actions", "advantage", "answer", "assessment",
                                               "backgrounds", "cisco", "city", "competencies", "consideration", "coverage",
                                               "creativity", "developed", "earn", "ensemble", "exp", "exploratory",
                                               "facilitate", "facing", "format", "hundreds", "identification", "integrating",
                                               "laws", "manipulating", "manual", "nation","obtain", "privacy", "profile",
                                               "run", "sharepoint", "validate", "abreast", "actions", "advance", "analyzes",
                                               "banking", "communications", "contractor", "dell", "di", "dimensional",
                                               "driving", "equipment", "experiments", "extracts", "guidelines", "intermediate",
                                               "logical", "mid",  "participates", "partnering", "perfect", "recruiter",
                                               "reduce", "response", "retail", "stay", "stored", "svm", "talented",
                                               "trusted", "view", "willingness", "collaborating", "curiosity", "cutting",
                                               "eeo", "establish", "faster", "form", "generation", "giants", "graduate",
                                               "holiday", "industries", "lambda", "list", "logistics", "look", "love",
                                               "low", "monthly", "place", "rapidly", "researchers", "seek", "sharing",
                                               "united", "veterans", "vital", "volumes", "worked", "alignment", "builds",
                                               "california", "consumer", "corporation", "discriminate", "employ",
                                               "harassment", "organized", "passions", "performed", "popnet","presently",
                                               "primarily", "professions", "recognized", "servers", "statement", "supplier",
                                               "target", "tooling", "total", "upskilling", "washington",
                                               "backend", "chance", "changing", "choice", "disciplines", "edgesource",
                                               "explain", "flows", "gartner", "informatics", "jmp", "joining", "marital",
                                               "past", "prescriptive", "qualitative", "savvies", "scale", "scaling",
                                               "simple", "soft", "spares", "tracking", "voluntary", "workforce", "youtube"
                                               "agencies", "algorithm", "authorization", "curious", "disabilities", "elder",
                                               "enthusiasts", "ethic", "explore", "extremely", "insight", "inspire", "involve",
                                               "leader", "leads", "permanent", "phc", "random", "startup", "supervision",
                                               "website", "weeks", "agencies", "apple", "boston", "command", "conclusions",
                                               "defined", "demand", "deploying", "engage", "feature",  "frequently",
                                               "gather", "investigators",  "locations", "mapreduce",  "offering",  "online",
                                               "patient", "release", "utilizes", "vegas", "verification", "youtube"
                                               "accommodations", "act","ask", "asked", "consistency", "data", "easy",
                                               "efficiently", "entrepreneurs", "flow", "houston", "ic", "increase", "las",
                                               "means", "medicine", "modify", "parallel", "selected", "things", "volume"
                                               "accommodations", "america", "annually", "caesars", "contributing",
                                               "descriptive", "detection", "difference", "differentiate", "engagement",
                                               "forecasts", "generative", "incumbent", "indicators", "investors",
                                               "measures", "newark", "secondary", "transforming", "youtube" "accommodations",
                                               "configuration", "consumers", "coordinating", "early", "funded", "live",
                                               "message", "output", "outside", "pricing", "prototype",  "recruiting",
                                               "regulations", "reusable", "shiny", "strongly", "studio", "video", "volume",
                                               "accommodations", "catalog", "checkout", "discover", "handle", "ii",
                                               "independent", "manages", "matching", "mathematical", "offices",
                                               "operationalizing", "particular", "population", "proof", "reject", "san",
                                               "sent", "summit", "youtube", "academic", "achievable", "architects",
                                               "behavior", "commensurate", "deadlines", "extracting",  "github", "haves",
                                               "hi", "inference", "informed", "initiative", "innovations", "ma", "measure",
                                               "recognize",  "roman", "safety", "upskill", "uthsc", "varying",
                                               "administrative", "competing", "consumption", "disabled", "draw", "genetic",
                                               "history", "implements", "industrial", "inform", "interfacing",
                                               "international", "meets", "met", "nuances", "organizing", "predict",
                                               "private", "pto", "querying", "schema", "spring", "thanks", "women",
                                               "accenture", "architecting", "connections", "costco", "entitled",
                                               "ethnicity", "follow",  "heart", "honda", "interact", "makes", "ny",
                                               "participating", "pattern", "pivot", "previous", "promote", "standardization",
                                               "terms", "train", "trials", "typically", "workplace", "yes", "accordance",
                                               "alteryx", "english", "evaluates", "exchange", "executive", "factors", "il",
                                               "involving", "juniper", "peer", "post", "prevention", "propose", "protocols",
                                               "respond", "reviewing", "sourcing", "speak", "taking", "weekly", "yale"
                                               "applicant", "ct", "documenting", "domains", "ehr", "enhancements", "expand",
                                               "expectations", "extend", "hypothesis", "image", "immediate", "interpreting",
                                               "minority", "prepares", "pull", "read", "salesforce", "scalability",
                                               "special", "spectrum", "successfully", "turn", "associate", "automating",
                                               "ba", "backed", "concise", "constantly", "defend", "demonstrates",
                                               "designed", "francisco",  "helpful", "hightouch", "home", "limitless",
                                               "loading", "mandatory", "mental", "personnel", "pl", "poly", "region",
                                               "thought", "version", "views", "yale", "accounts", "applicant", "audience",
                                               "capital", "cinqcare", "cluster", "complexity", "dax", "forms", "formulas",
                                               "fun", "generating",  "lot", "materials", "north", "ownership", "papers",
                                               "proud", "simply", "simulation", "store", "tuning", "vendor", "verify",
                                               "allow", "applies", "automatically", "convey", "created", "embrace",
                                               "emphasis", "empower", "experimental", "gaming", "interaction", "items",
                                               "lift", "limitations", "marts", "mavrck", "mobile", "native", "niche",
                                               "pride", "repeatable", "req", "transit", "audits", "citizen", "comes",
                                               "contributes", "correct", "experienceexcellent", "experimentation", "fastest",
                                               "handling", "happenings", "multidisciplinary", "nc", "nj", "ready",
                                               "recognition", "reimbursement", "relationship", "retaliation", "skyepoint",
                                               "stakeholder", "timelines", "tn", "transcript", "tx", "typical", "visibility",
                                               "concept", "construction", "easily", "economic", "ecosystem", "higher",
                                               "improves", "initial", "interpretation", "interprets", "lineage", "lines",
                                               "minded", "operates", "priority", "relate", "relocation", "screening",
                                               "semi", "story", "table", "targeted", "treatment", "unlock", "workers",
                                               "accredited", "actual", "amazing", "annual", "attitude", "audit", "billions",
                                               "example", "flexibility", "markets", "migrating", "onboarding", "pragmatic",
                                               "proper", "requisite", "resolving", "satisfying", "smart", "takes",
                                               "teamwork", "aggregates", "app", "assessments", "assignments", "assurance",
                                               "balbix", "connection", "developments", "device", "engine", "factory",
                                               "foundation", "lieu", "little",  "mind", "probability", "quick",
                                               "segmentation", "summarize", "ae", "algebra", "alpha", "array", "checks",
                                               "close", "graphs", "impactful", "ingest", "integrations", "intended", "interfaces",
                                               "mhp", "recommendation", "resourceful", "rigorous", "trading", "traditional",
                                               "transparency", "true",  "compelling", "complies", "consultants", "courses",
                                               "dataexperience", "devices", "drilling","enrich", "entrepreneurial", "kindly",
                                               "noticed", "novel", "particularly", "programmingspring", "scoring", "simplify",
                                               "accessible", "conditions", "conducts", "confidentiality", "elastic",
                                               "eligibility", "enabling", "feel", "lmi", "mentor", "mentoring",
                                               "pharmaceutical", "qa", "regular", "conviction", "coordination",
                                               "corporate", "depending", "distribution", "functionality", "improved",
                                               "infrastructures", "investigation", "journey", "json", "near", "optimizes",
                                               "refine", "sponsorship", "activity", "add", "continuously", "contracts",
                                               "countries", "effectiveness", "evolving", "ex", "hello", "legacy",
                                               "massive", "meaning", "media", "sagemaker", "sync", "teammates", "watch",
                                               "apps", "devise", "distributions", "drives", "entire", "freedom", "loss",
                                               "root", "sound", "speed", "sr", "streamline", "xml", "connecting",
                                               "constant", "construct", "dashboarding", "dc", "labor", "looker", "los",
                                               "makers", "managed", "suppliers", "synapse", "tackling",
                                               "collaborators", "drawing", "environmental", "exploration", "fundamentals",
                                               "hourly", "huge", "identifies", "iii", "missions",  "normalization",
                                               "specification", "starting", "summaries", "advise", "align", "angeles",
                                               "athena", "charlotte", "charts", "consultant",  "domino", "hospitals",
                                               "infotech", "inventory", "preparing", "schedules", "transaction",
                                               "accepting", "accident", "accounting", "acumen", "adept", "adhere",
                                               "allows", "anomalies",
                                               "approved", "aputure", "associates", "biomedical", "board", "bourne", "cap",
                                               "causal", "classes", "combine", "contributions",
                                               "contributor", "controls", "cores", "corrective", "demands",
                                               "departments", "disparate", "division", "exactly", "expect", "exploring",
                                               "fair", "fix", "forests", "founded", "generated", "generous", "going",
                                               "hardware", "headquartered", "hermitage", "highest", "ideally", "identified",
                                               "illness", "influence", "initiate", "innovate", "intellectt", "joy", "kind",
                                               "laid", "linkages", "matters", "md", "med", "method", "navigation",
                                               "northeastern","objects", "obsessed", "oh", "oversight", "pa", "parental",
                                               "pre", "presents", "processors", "procurement", "producing", "productivity",
                                               "prototypes", "purview", "qlik", "regardless", "requested", "revenue",
                                               "rich", "rv", "save", "scheduling",  "seeks", "serves", "signal", "skype",
                                               "sme", "spend", "stock", "substituted", "sustain", "sustainable", "updates",
                                               "ut", "utility", "worldwide", "approvals", "articulate", "assignment",
                                               "attend", "brand", "budget", "calculations", "carolina", "choose",
                                               "clinics", "codes", "commerce", "communicates", "completed", "completeness",
                                               "containerization", "context", "continued", "court", "craft", "cursors",
                                               "derive", "describing", "desk", "dollar", "econometrics", "educate",
                                               "effect", "elite", "enables", "enjoys", "entertainment", "epidemiology",
                                               "evaluating", "evaluations", "excited", "fax", "final", "fuel", "functionally",
                                               "hour", "house", "implemented", "info", "map", "material", "meeting",
                                               "messaging", "money", "multivariate", "paperwork", "park",  "peers",
                                               "performant", "perspective", "powers", "premium", "properties", "protingent",
                                               "quantify", "ripple", "roadmap", "route", "running", "semantic", "serving",
                                               "sessions", "standardized", "stantec", "statistician", "statisticians",
                                               "telemedicine", "thorough", "threads", "thrive", "tradoc", "trained",
                                               "tuition", "twilio", "videos", "virginia", "accomplish", "adoption",
                                               "aggregation", "artifacts", "attributes",  "auditing", "austin",
                                               "awareness", "bank", "bar", "cause", "cdf", "centered", "challenge",
                                               "civilian", "crop",  "discussion", "discussions", "display", "figures",
                                               "fine", "firms", "florida", "forecast", "forest", "forward", "foster",
                                               "hidden", "immediately", "implementations", "initially", "inquiries",
                                               "insightful", "inspiring", "intelligent", "interactions", "interesting",
                                               "intersection", "intriguing", "irb", "judgment",  "knowledgeable", "larger",
                                               "launch", "likely", "maintainable", "manufacturing", "outperform", "outstanding",
                                               "path", "patients", "pig",  "profiling", "pursue", "reference", "relating",
                                               "relative", "residents", "resolution", "respect", "retrieval", "reverse",
                                               "routine", "situations", "steps", "strive", "sub", "submit", "transfer",
                                               "transformations", "tree", "valuable", "vehicle", "venture", "verbally",
                                               "verified", "windows", "yearly", "aligned", "arise", "arlington", "asap",
                                               "assisting", "boundaries", "brands", "buy", "debugging", "demanded",
                                               "departmental", "destination", "director", "educational", "efficiencies",
                                               "elasticsearch", "engines", "enhancing",  "examples", "executives",
                                               "flooded", "game", "generally", "hired", "hold", "idea", "incorporate",
                                               "increasing", "mail", "mentality", "mobility", "moving", "orchestration",
                                               "owner", "populate",  "potentially", "prioritization", "proactively",
                                               "promotes",  "pythonexperience", "qualification", "rapid", "risks",
                                               "sensitivity", "shape", "ship", "sit", "skillset", "specialized",
                                               "specializes", "sponsor", "sports", "starter", "storytelling", "stream",
                                               "strengths", "students", "succeed", "syncing",  "tactical", "tagging",
                                               "tailored",  "upgrades", "urgent", "usaid", "usc", "valued", "variable",
                                               "vary", "versed",
                    "10", "100", "12", "20", "2022", "25", "30", "40", "401k", "50", "ab", "afin", "agoda", "ainsi",
                    "alternance", "analyse", "andor", "ans", "arbeiten", "aufgaben",
                    "bereich", "berlin", "besoins", "bieten", "bilgi", "booking", "cadre", "canada",
                    "canonical", "cest", "charge", "chez", "cicd", "civil", "collaborateurs", "compétences",
                    "connaissance", "consider", "continue", "crossfunctional", "customized", "cuttingedge", "cv",
                    "dabei", "datadriven", "daten", "decisionmaking", "deutsch", "does", "doing",
                    "données", "dont", "dun", "dune", "développement", "développer", "ecommerce", "encourage",
                    "endtoend", "entreprise", "entwicklung", "environnement", "erfahrung", "europe",
                    "expérience", "fastpaced", "formation", "france", "fulltime", "gemeinsam",
                    "gestion", "globally", "groupe", "gute", "handson",  "highlighting",
                    "highquality", "hr", "ibm", "ilgili", "internet", "just",  "kannst", "kenntnisse",
                    "konusunda",  "kunden", "largescale", "lentreprise", "linkedin",  "listed",
                    "ll", "london", "longterm", "lösungen", "main", "make", "mehr", "meta", "mettre", "microsoft",
                    "million", "millions", "mise",  "monde", "métier", "métiers", "network", "niveau",
                    "nontechnical",  "offre", "olarak", "organisation", "outils", "paris", "participer", "pays",
                    "pension", "point", "poste",  "powered", "pregnancy", "problemsolving", "processus",
                    "profil", "projet", "projets", "qualité", "rd", "readily", "realtime",
                    "recherche", "regarding", "rejoindre", "scheme", "sector", "sowie", "stage", "studium", "tant", "technique",
                    "technologien", "teil", "travail", "travailler", "trust", "turkey", "uk", "uncover", "unternehmen",
                    "used", "using", "various", "webbtree",
                    "wellbeing", "worlds", "youll", "youre", "zb", "zukunft", "école", "équipe", "équipes",
                    "000", "15", "2023", "35", "500", "80", "90", "abgeschlossenes", "accept", "accompagner",
                    "activités", "aim", "alongside", "ambitious", "asia",
                    "assurer", "avantages","bases", "bewerbung", "bonne", "bringing",
                    "bringst", "ca", "capability", "capacité", "centre", "certain", "chacun", "characteristic",
                    "characteristics", "cloudbased", "coaching", "communauté", "conception", "connaissances", "conseil",
                    "consultancy", "contrat", "contribution", "country", "cover", "criminal", "criteria", "crm",
                    "croissance", "crossover", "crucial", "créer", "dafür", "dbt", "desirable", "différents",
                    "digitale", "diversité", "domaine", "donnée", "drug", "dynamique", "emploi", "employeur",
                    "empowered", "entreprises", "erfahrungen", "esprit", "fintech", "forefront",
                    "formations", "fostering", "fragen", "frankfurt", "freuen", "frontend",
                    "games", "geliştirme", "gerne",  "grande", "grâce",  "hamburg",
                    "hast", "hear", "informatik", "informations", "informatique", "innerhalb", "internationale",
                    "intégration", "istanbul", "iş", "kpis", "legally",
                    "ligne", "léquipe", "maîtrise", "menschen", "modèles", "mwd", "nationalities", "net",
                    "neue", "nouvelles", "openclassrooms", "option", "page", "parttime",
                    "payment", "prix", "proactive", "produits", "programme", "promotion", "proposition",
                    "realworld", "recherchons", "recherché", "recrutement", "remotely",
                    "rewards", "réaliser", "rôle", "s3", "safe", "sahip",  "secteur",
                    "shared","solely", "specialist", "stratégie",
                    "suchen", "suivi", "supported", "systèmes", "talents", "td", "thats",
                    "toutes", "traitement", "télétravail", "umgang", "umsetzung", "units", "unterstützen", "uptodate",
                    "vacation", "veri",
                    "weiterentwicklung", "wellness", "wider", "wissen", "worklife", "yazılım", "zusammenarbeit",
                    "également", "œuvre",
                    "2024", "60", "according", "adapt", "aimed", "analyser",
                    "ancestry", "anforderungen", "anglais", "arbeitest", "automotive", "autres",
                    "beratung", "bereichen", "berufserfahrung", "booz",
                    "capgemini", "carrière", "changement", "condition", "connects", "contexte", "création", "daytoday",
                    "determined", "devez", "différentes", "discuss",  "don", "eager", "emails",
                    "employers", "encourages", "englischkenntnisse", "entre", "entwickeln", "entwickelst",
                    "expanding", "flights", "forte", "framework","geospatial", "gestalten",
                    "happy", "healthy", "hiringjobsailive", "holdings", "id", "ideen",
                    "implementierung", "incentive", "indepth", "ingénieur", "interne", "iot",
                    "jour", "jours", "keen", "kişisel", "knowhow", "kolleginnen",
                    "marque", "merit", "mode", "modélisation", "möglichkeit",
                    "mühendisliği", "networking", "notice", "numérique", "offered", "offerings", "olan",
                    "optimisation", "outil", "partenaires", "participation", "partnership", "pass", "pearson",
                    "performances", "period", "pivotal", "plateforme", "plusieurs", "politique",
                    "postuler", "pratiques", "premier", "principal", "projekte",
                    "pôle", "quotidien", "react", "really", "relation", "responsable", "result",
                    "sahibi", "sens", "shaping", "shift", "siemens",
                    "single", "sites", "situation", "spirit",
                    "stateoftheart", "statistiques", "stories", "suivantes", "supportive", "sustainability", "sécurité",
                    "takip", "technologie", "temps", "terraform", "topics",
                    "toptier", "toronto", "transport", "transportation", "travelers", "trilogy", "truly", "tssci",
                    "umfeld", "unterstützt", "unterstützung", "usd", "vibrant", "vie", "weltweit", "window", "worldclass",
                    "yönetimi", "yıl", "zusammen", "çalışma",
                    "49", "6000", "accelerate", "advertising", "agreement",
                    "aktiv", "allowance", "ambition", "améliorer", "analysing", "arbeit",
                    "auprès", "autour", "awards", "az", "b2b", "bac5", "bangkok", "beim",
                    "bereits", "bien",  "bonnes", "bord", "bringen", "brings", "bölümlerinden",
                    "cable", "celebrate", "centers", "channels", "clé", "companys", "comprendre", "concevoir",
                    "confidential", "connected", "contribuer", "course", "cœur", "danalyse", "delivered",
                    "delivers", "dependent", "differences", "diplôme", "discounts", "définition",
                    "empowers", "encouraged", "engaging", "englisch", "enjeux", "erfolg", "erfolgreich", "erp", "erste",
                    "etou", "evolution", "exploitation", "facilities", "fantastic", "fluent",
                    "fonction", "food", "fähigkeiten", "german", "gmbh",
                    "ground", "handicap", "head", "homeoffice", "ia", "idealerweise",
                    "impacts", "incentives", "installation", "internes", "intégrer",
                    "keeping", "konzeption", "lanalyse", "landscape", "leben",
                    "manchester", "marketplace", "mathematik","munich",
                    "ngilizce", "notamment", "opensource", "optimierung", "organisations",
                    "parties", "phase", "phases", "posted", "première", "prise",
                    "rapports", "redshift", "regularly", "rejoignez", "represented",
                    "representing", "retention", "rewarding", "rund", "répondre", "résultats",
                    "satisfaction", "seamless", "singapore", "society",
                    "société", "spoken", "sport", "strength", "student", "stuttgart",
                    "sujets", "tag", "tage", "technological", "technologique"
                    "touch", "translating", "travers", "undoder", "unsolicited", "utilisateurs", "verfügst",
                    "weitere", "wirtschaftsinformatik",
                    "wort", "études", "étudiants", "évoluer",
                    "23", "achieving", "activité", "additionally", "advice", "agilen", "air",
                    "apprendre", "arbeitsumfeld", "arbeitszeiten",
                    "architectural", "biggest", "billion", "bonuses",
                    "cabling", "campaign", "campaigns", "candidature", "cas", "chicago", "childbirth", "climate",
                    "competence", "confident", "constraints", "consult", "conversion", "cultivating", "datarelated",
                    "datenbanken", "digitalen", "diplômante", "domaines", "décole", "einsatz",
                    "equality", "etcexperience", "everify", "executing", "experienceexperience", "face",
                    "facebook", "fastgrowing", "fees", "flux", "fort", "genel", "germany",
                    "giving", "got", "grade", "gym", "hakkında", "hand",
                    "individuelle", "inhouse", "instagram", "internship", "invest",
                    "jobrelated", "known", "langages", "letter",
                    "living", "luxe", "maps", "marché", "maximum", "minds", "mix", "mois",
                    "münchen", "müşteri", "olmak", "opens", "optimiser",
                    "opérations", "outlined", "partie", "payments", "permettant", "philadelphia",
                    "pioneering", "plein", "powerful", "powerpoint", "pratique", "preuve",
                    "principales", "problématiques", "produit", "professionnelle", "programmation", "progression",
                    "projekten", "proposer", "protect", "purchase", "received", "recruit",
                    "reflects", "regional", "removed", "rendre", "rolle", "réalisation", "sectors", "spam",
                    "stages", "statistik", "steht", "suitable", "talend", "talk",
                    "technologique", "thirdparty", "tomorrow", "touch", "transition", "tâches", "türkiye",
                    "vacancies", "valeurs", "veille", "verantwortung", "vergleichbare", "verschiedenen", "voice",
                    "whilst", "won", "yeni", "évolution",
                    "36", "accessibility", "accompagnement", "adjustments",
                    "altersvorsorge", "ambitions", "amsterdam", "analiz", "army",
                    "arrangements", "austausch", "authorized", "awardwinning", "belief",
                    "belonging", "button", "cancer", "cdi", "collective", "communicator",
                    "completing", "component", "compte", "consistently", "continually", "costs", "creed",
                    "definition", "denver", "designers", "destek", "detailoriented", "deutschlands",
                    "dexpérience", "dingénieur", "discretionary", "disposez", "déploiement", "edinburgh",
                    "embedded", "enthusiastic", "envie", "erwartet", "european", "eye", "findest",
                    "focuses", "focusing", "fournir", "funding",
                    "grands", "gérer", "hypotheses", "identifier",
                    "iletişim", "importance", "indicateurs", "informationen", "inside", "institutions", "intern",
                    "involves", "issue", "iyi", "jerusalem", "komplexe",
                    "kundinnen", "langage", "lensemble", "maintenir", "manière",
                    "mark", "matière", "maximize", "methoden",  "minutes", "miteinander",
                    "mobilité", "motivation", "méthodes", "neuen",
                    "orientations", "parcours", "partnerships", "personalized", "places", "plusexperience",
                    "prendre", "pro", "problèmes", "prozesse", "prêt",
                    "qualifikation", "reality", "realize", "reconnu", "reflect", "represents", "reward",
                    "salaries", "seattle", "selfstarter",
                    "selon", "sensitive", "seoul", "setup", "skillsability", "souhaitez",
                    "sowohl", "stability", "style", "targets", "tax",
                    "technische", "telaviv", "tell", "tercihen", "themen", "threat", "toute", "trainings",
                    "turkish", "ultimately", "vacancy", "workshops", "üzere",
                    "10000", "13", "18", "200", "2010", "50000", "acceptance", "accurately", "acv", "adesso",
                    "advisory", "aider", "allowing", "ankara", "antler",
                    "artificielle", "atlanta", "attracting", "aufbau", "autonome", "autonomie",
                    "bancaire", "bangalore", "barriers", "besoin", "beste", "bewerben",
                    "bitte", "c2c", "champion", "collecte", "comfort", "confidence", "construire",
                    "dice", "disease", "distance", "dynamics", "economy", "effort", "empowering",
                    "engagements", "equitable", "essen", "establishing", "estate", "extra", "facility",
                    "fixed", "friday", "gehören", "gerekli", "greater",
                    "görev", "herkunft", "incidents", "innovating",
                    "innovativen", "integral", "interesse", "investments", "invite",
                    "kingdom", "konularında", "leverages", "mechanical",
                    "membership", "mentorship", "mitarbeiterinnen", "montreal",
                    "motivés",  "nachhaltige", "navigate", "newcastle", "news",
                    "objectif", "objectoriented", "opportunityaffirmative", "opportunités", "partager",
                    "persons", "pilotage", "produkte", "promoting", "prototyping", "purposes",
                    "push", "qualités", "rahmen", "ranges", "referral", "remotefirst", "return",
                    "riyadh", "réseau", "santé", "screens",
                    "secteurs", "selflearner", "selfmotivated", "selfservice", "skillsexperience",
                    "speaking", "standort", "submitted", "superior",
                    "synnex", "système", "taipei", "takım", "teamgeist", "teknolojileri",
                    "thing", "trade", "useful", "utilisation", "uygun", "vancouver",
                    "vergleichbaren", "vielfalt", "wealth", "welt", "whats", "üniversitelerin", "şekilde",
                    "11", "2000", "2004", "2021", "45", "accountability", "adherence", "advancement",
                    "aimez", "algorithmes", "alias", "alternative", "analysen",
                    "ausbildung", "behaviours",
                    "bietet", "broader", "candidat", "candidats", "cash", "closing", "complexes",
                    "compréhension", "conferences", "covid19", "cultural", "digitalisierung",
                    "discount", "divisions", "dna", "dresden", "dublin", "ethnic",
                    "experiment", "families", "français", "fundamental", "ganz", "geographic",
                    "gut", "half", "held", "hf", "highperformance", "hinaus", "hit",
                    "idéalement", "innovantes", "interests", "jahre",
                    "justifiez", "kollegen", "kultur", "köln",  "laise",
                    "leipzig", "lemploi", "lifestyle",  "luxembourg", "madrid", "maîtrisez",
                    "mehrjährige", "melbourne", "miami",  "mitarbeiter", "moderne",
                    "möchtest", "möglichkeiten", "nationality", "nombreux",
                    "nécessaires", "ones", "outputs", "parts", "placement", "possibilité",
                    "preference", "programmes", "proje", "property", "proprietary", "pwc",
                    "raise", "relations", "remain", "reportings", "responsabilités", "rights",
                    "rigueur", "savoir", "sending",
                    "sistemleri", "skillsstrong", "sophisticated", "sounds",
                    "spaß", "specialists", "standorten", "startups", "stelle", "sydney",
                    "tackle", "tdd", "tokyo", "transactions", "transparent",
                    "unlimited", "unterschiedlichen", "utilization", "valid", "vb", "vehicles", "vers", "verschiedene",
                    "verständnis", "visiting", "weve", "yi", "young", "çalışmasına", "évolutions",
                    "3rd", "60000", "academy", "acquérir", "acteur", "actifs", "advancements",
                    "alexandria", "answers", "apprentissage",
                    "attractive", "audio", "autonomous", "barcelona",
                    "beneficial", "betriebliche", "bilgisayar", "brief", "brightest", "cabinet",
                    "cables", "carry", "cgi", "cherchez", "cologne", "combined", "coming", "container", "continues",
                    "copy", "demonstrating", "depend", "derecede", "deren", "detroit", "deutschland",
                    "diploma", "dortmund", "drivers", "duty", "déjà", "eng", "enhanced", "entrylevel",
                    "errors", "erstellung", "estonia", "evaluated", "evidence", "expansion",
                    "expériences", "founders", "genau", "gibt",
                    "grasp", "guarantee", "hcmc", "hierarchien",
                    "industrie", "ingénierie", "inperson", "internationalen", "investing", "jakarta",
                    "kapsamında", "lavenir",
                    "leidenschaft", "lien", "liés", "lunch", "maitrise", "mesure",
                    "milan", "newyork", "nutzung",
                    "oakland", "objective", "occasional", "onpremise", "orlando", "oversee", "pace", "partir",
                    "perth", "political", "portland", "postes", "presence", "prérequis",
                    "reading", "recently", "recommandations", "reconnue",
                    "representative", "restaurant", "sanfrancisco",
                    "setzen", "shanghai", "shortterm", "skyvera", "smarter",
                    "stockholm", "striving", "teknik",
                    "tickets",  "ventures", "verantwortlich", "wachsen", "wed",
                    "wichtig", "yer", "yüksek", "zurich", "ürün",
                    "24", "accountable", "agreed", "alanında", "alter",
                    "analystdata", "ansible", "anwendungen", "arıyoruz",
                    "atmosphere", "away", "bali", "banque", "beijing",
                    "bestinclass", "brno", "budapest", "cairo", "caring", "centaines", "coach",
                    "conversations", "dedication", "deneyim", "determining", "discretion",
                    "disposition", "doptimisation", "dubai", "département", "départements", "ekip",
                    "electric", "electronics", "environnements",  "everyday", "evolve",
                    "fitness", "forces", "freelance", "fulfilling",
                    "hongkong", "immer",
                    "katowice", "kontrol", "krakow", "kualalumpur",
                    "lasting", "launched", "loan", "losangeles",
                    "létat", "malta", "manila", "mieux", "min", "mindestens",
                    "msc", "multitask", "numerous", "optimise", "optional", "osaka",
                    "oslo", "paths", "phuket", "plateformes", "players", "plays",
                    "prague", "praktische", "quo", "raum", "religious",
                    "residency", "rio", "rome", "room", "salvador", "sandiego", "sanjose",
                    "satış", "schaffen", "schrift", "select", "shall",
                    "shenzhen", "shopping", "smooth", "spanning",
                    "staying", "stockage", "suit", "taux", "technischen", "tel",
                    "ticket", "topic", "unabhängig", "urlaub", "uygulama", "vast",
                    "volunteer",
                    "warsaw", "wroclaw",
                    "1000", "72", "advancing", "ahead", "aid", "airbus",
                    "aktuellen", "alrayyan", "annum", "année", "arbeitgeber",
                    "attraktive", "augenhöhe", "autonomy", "bandung",
                    "bewerbungen", "blockchain", "bologna", "bzw", "choix", "collaborer",
                    "connectivity", "darauf", "dautres", "deal", "deeply",
                    "définir", "déquipe", "entièrement", "finally", "flat",
                    "florence", "fukuoka", "fullstack", "fundierte", "garantir",
                    "genetics", "giza", "hanoi", "headquarters",
                    "histories", "humaine", "images", "influencing", "internally",
                    "jeddah", "kaohsiung", "kommunikation",
                    "laboratory", "lalternance", "led", "lodz",
                    "lyon", "mdm", "measurable", "mecca", "medina", "mitarbeitenden",
                    "modèle", "morgen", "motivé", "möglich", "nagoya", "naples",
                    "newdelhi", "newly", "okinawa", "opening", "opérationnelles", "ostrava",
                    "outcome", "palermo", "possibility", "poznan",
                    "professionnel", "publications", "rates", "register", "relationnelles",
                    "requises", "restaurants", "restful", "retenue", "rh", "richtig",
                    "sdlc", "section", "sistem",
                    "stanbul", "standorte", "survey", "synthèse",
                    "taichung", "tainan", "technologiques", "telecommunications", "threats", "thrives",
                    "turin", "unable", "unless", "venice", "w2", "yokohama", "übernimmst",
                    "14", "ajoutée", "allianz", "analytique",
                    "analytische", "aptitude", "arbeitsweise", "architekturen", "assessing",
                    "axa", "belong", "betrieb",
                    "birlikte", "bremen", "capacités", "cars", "children", "choices", "clés", "coffee", "contacted",
                    "deneyimi", "deutschkenntnisse", "driver",
                    "durable", "décision", "défis", "emergency", "entering", "entity", "entretien", "estimate",
                    "ethical", "etmek", "fidelity", "fin", "financée", "flexibles", "fluency",
                    "führenden", "gained", "grand",
                    "greatest", "guiding", "harness", "helfen", "herausforderungen", "highlevel",
                    "historical", "included", "income", "insbesondere",
                    "interdisziplinären", "komplexer",
                    "limits", "marques", "mensch",
                    "mobiles", "modernen", "modernization", "modules", "monday",
                    "mêlant", "objectifs", "odaklı",
                    "persönlichen", "planet", "plant", "possibilities",
                    "preprocessing", "pressure", "protecting", "quarterly", "receiving",
                    "recrutons", "regelmäßige", "rely", "requiring", "schon",
                    "semaine", "serverless", "skillsexcellent",
                    "souhaité", "spannende", "stacks",
                    "started", "surveillance",  "tasarım", "théorie", "toulouse",
                    "ui", "varied", "verfügung", "verilerin", "water",
                    "weiterbildungsmöglichkeiten", "wirtschafts", "wrangling", "yönetim", "zero",
                    "100000", "27", "accès", "acting", "addressing", "affichons", "aims",
                    "amené",  "angabe","authentic",
                    "behinderung", "bewerbungsprozess", "bewirb", "bienêtre",
                    "büro", "causes", "chapter", "combining", "commerciales", "comply", "confluence",
                    "continents", "cooperation", "corresponding", "covered", "covering", "crafting", "curieuxse",
                    "datenanalyse", "daujourdhui", "default", "deshalb", "desktop", "dinsertion",
                    "développements", "embraces", "embracing", "entities", "equally", "erreichen",
                    "express", "flexibilität", "frank", "french",
                    "gehaltsvorstellung", "geography", "gestaltest",
                    "gouvernance", "groundbreaking", "guard", "gutes", "hospital",
                    "inception", "instrumental", "investigate", "izmir",
                    "konzepte", "lets",
                    "léducation","mondial",
                    "mutuelle", "neuer", "occuper", "offres",
                    "parking", "philosophy", "pointe", "pole", "pool",
                    "principalement", "profit", "programmierung", "ranging", "recrute",
                    "refining", "refresh", "respected", "robert", "say", "sağlamak",
                    "scheduled", "scolarité",
                    "spécifications", "stehen", "suivre", "systematic",
                    "teknoloji", "telus", "traitements", "travaux",
                    "underwriting", "unternehmenskultur", "vorteil", "webbased",
                    "workday", "épaulent", "étroite",
                    "16", "advisors", "affaires", "aide", "aktif",
                    "ambiguous", "analitik", "années",
                    "basé", "blend", "cassandra", "colorado", "complémentaires",
                    "confiance", "considering", "cultures", "curiosité", "darüber", "december",
                    "deneyimli", "described", "direkt", "durée", "düsseldorf", "enthusiasm",
                    "expenses", "export", "externe", "fachliche", "fortes", "fournie",
                    "genesis10", "geschlecht", "gives",
                    "goto", "großen", "hakim", "happen",
                    "incident", "indicated", "itlösungen",
                    "logiciels", "maitrisez",
                    "medium", "meilleure", "meilleures", "mis", "miss",
                    "moment", "möchten", "named", "obtaining",
                    "partage", "paying", "persönliche", "placing", "plattform",
                    "productive", "profiles", "proposons", "provision", "proximité", "pushing",
                    "raporlama", "reason", "resilient", "responsabilité",
                    "roadmaps", "rémunération", "réussir", "savez", "savoirfaire",
                    "searching", "seasoned", "sexueller", "simultaneously",
                    "softwareentwicklung", "sorgen",
                    "strategischer", "stratégiques", "streams", "stronger", "substantial",
                    "turning", "twitter", "utilisant","volunteering", "voran",
                    "waiting", "weiterbildung", "weiteren", "weltweiten", "workload", "yapmak",
                    "2020", "300", "365", "abroad", "adaptable", "aerospace", "agiles",
                    "american", "amélioration", "analizi",
                    "appropriately", "approval", "asking", "assuming", "aujourd", "aujourdhui", "authoring", "average",
                    "backup", "begeisterung", "begin", "beraten",
                    "bilgisine", "box", "branch", "branchen", "bricks", "bureaux", "carbon", "chances",
                    "cloudnative", "conceptual", "consecutive", "contrôle", "crime", "créativité", "cultivate",
                    "datengetriebenen", "daxes", "dealing", "decades", "demonstrable",
                    "diagrams", "digitalization", "domestic", "doutils", "east", "einfach",
                    "employing", "enforce", "engaged", "ersten", "extent",
                    "fachlichen", "fl", "fokussieren", "folders", "foreign", "forwardthinking", "fosters",
                    "fund", "genauso", "gold",
                    "grandes", "große", "gängigen", "hannover", "hearing", "helm",
                    "holding", "httpswwwpoleemploifr", "imagine", "incoming",
                    "internationales", "internen",
                    "kept", "korunması", "lean", "lernen", "lgbtq",
                    "lifetime", "lisans", "log", "longer", "mastery", "maternity",
                    "membres", "navigating", "nigel",
                    "nitelikler", "november", "nutzen", "nächstmöglichen",
                    "occasionally", "opérationnelle", "organisational", "orientierung", "ouverts",
                    "partenaire", "partnered", "passionnée", "password", "plenty",
                    "prenantes", "processed", "promotions", "rattaché",
                    "relationnel", "reset", "résoudre",
                    "seen", "sell", "selves", "servicing", "signavio", "significative",
                    "spécialisé", "spécifiques",
                    "strategie", "summer", "taille", "tangible", "tarafından", "temporary",
                    "teradata", "tight", "transformative", "transformer", "trend",
                    "umfangreiches", "vaccination", "virtual", "visual", "visualisation", "visualisations",
                    "visualizations", "visualize", "wachstum", "zeitpunkt", "zone", "çözme",
                    "çözüm", "équivalent",
                    "aware", "bac", "dive", "fraud", "gap", "gaps", "gas",  "hoc", "hse", "hub", "jahr",
                    "lab", "llm", "llms", "mi", "saas", "sap", "secure", "st", "warehouse", "web"
                    ]

target_keywords = ["adhoc", "adobe", "aiml", "airflow", "amazon", "android", "apache", "api", "aws", "azure", "bash",
                   "batch", "bi", "bigquery", "css", "cvs", "db", "devops", "docker", "etl", "etlelt", "excel", "gcp",
                   "git", "gitlab", "globe", "glue", "h1b", "hadoop", "hive", "html", "ios", "java", "javascript",
                   "jenkins", "kafka", "kpi", "kubernetes", "lakes", "linux", "matlab", "microservices", "ml", "mlops",
                   "mongodb", "mysql", "nlp", "nosql", "numpy", "pandas", "plsql", "postgres", "postgresql", "powerbi",
                   "pyspark", "pytorch", "python","rds", "sas", "scala", "scikitlearn", "scratch", "shell", "snowflake", "solid",
                   "spark", "spss", "sql", "ssis", "ssrs", "tableau", "tableaux", "tensorflow", "tsql", "ubuntu", "vba",
                   "node.js", "angular", "react", "spring", "django", "flask", "unity", "unreal engine", "databricks",
                   "jupyter notebook", "chef", "puppet", "terraform", "ansible", "vue.js", " r", "cassandra", "couchbase",
                   "kotlin", "heroku", "netlify", "puppeteer", "selenium", "coffeescript", "mvvm", "mvp", "mvi"]